version: "3"

services:
  goMicro:
    build:
      context: src
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mysql
    links:
      - redis
      - mysql
  redis:
    image: redis:6.0.8
    container_name: go-micro-redis
    ports:
      - "6381:6381"
    volumes:
      - /etc
  mysql:
    image: mysql:latest
    container_name: mysql8
