version: '3.0'
services:
  canal-server:
    image: canal/canal-server:v1.1.5
    container_name: canal-server
    ports:
      #canal默认端口号
      - "11111:11111"
    environment:
      #设置从库id，不能与主库id相冲突
      - canal.instance.mysql.slaveId=222
      - canal.instance.master.address=192.168.0.103:3306
      # mysql 复制账号
      - canal.instance.dbUsername=canal
      - canal.instance.dbPassword=canal
      - canal.mq.topic=example
      #数据库名.表名
      - canal.instance.filter.regex=canal_redis.baseCreditInfo
#    volumes:
#      - /tmp/canal/logs/:/usr/local/dockercompose/canal/logs/
