version: '3.0'
services:
  app-tp3.23:
    build:
      context: ./
      dockerfile: php.Dockerfile
    container_name: app-fpm
    volumes:
      - ./:/var/www/laravel
    depends_on:
      - app-redis


  app-nginx:
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    container_name: app-nginx
    volumes:
      - ./:/var/www/laravel
    ports:
      - "8082:80"
    depends_on:
      - app
